### ISSUE TITLE
File Decryption is not working

### ISSUE THREAD

**Issue by Suleman-Elahi** [penghuili/PreCloud#2]
On Android(Samsung m40, Android 11) it can encrypt files but is not able to decrypt them. I either get a decryption error or it fails to upload the decrypted file to Google Dive. And even if it uploads the file, it is the same encrypted file.

Besides, all the files that are encrypted by it should be saved on internal storage. Maybe make a precloud folder and save all the encrypted files in it.

**Comment by penghuili** [comment]
Thank you @Suleman-Elahi for the feedback!
I will look into it.

by the way, files are copied to internal storage before encryption, for example if you go to the settings screen, you will see there are some caches.

**Comment by Suleman-Elahi** [comment]
Yes I can see the "cache" status but where exactly the encrypted files are stored?

**Comment by penghuili** [comment]
Hi @Suleman-Elahi , I found the reason for `even if it uploads the file, it is the same encrypted file.`.

When I upload the decrypted file, I chose the wrong file type. 

it's fixed in version 1.0.7, could you download it from Play store and have another try?

---

Regarding the decryption error, if you still get them, let me know, I will check again.

---

And about the internal storage topic, currently all encrypted and decrypted files are saved in the internal storage for the app, you can't access them from the android file system.

I may introduce a section to view cached files and give options to download or delete them.

**Comment by Suleman-Elahi** [comment]
Yes thanks man. I works now.

**Comment by penghuili** [comment]
Great! I will close the issue then
